export const articles = [
    {
      id: "1",
      title: "lunette femme",
      poster: "https://ae01.alicdn.com/kf/H6532f91a52014ab4b08f1e8e4a046c5df/Begreat-Oculos-Lunette-De-Soleil-Femm-Classic-Retro-Square-Sunglasses-Women-Brand-Vintage-Travel-Small-Rectangle.jpg_220x220xz.jpg_.webp",
      decription:
        "Begreat Oculos – lunettes De Soleil classiques rétro carrées pour femmes, marque Vintage voyage petites lunettes De Soleil rectangulaires",
      rate: 2,
      sexe:'f',
      prix: '25 TND',
      livraison: 'n',
      disponibilite: 'd',
    },
    {
      id: "2",
      title: "lunette homme",
      poster:
        "https://ae01.alicdn.com/kf/HTB1n33FyxuTBuNkHFNRq6A9qpXaT/VEITHDIA-Men-Sunglasses-Vintage-Aluminum-TR90-Photochromic-Polarized-UV400-Lens-Fashion-Sun-Glasses-Eyewear-For-Male.jpg_220x220xz.jpg_.webp",
      decription: "VEITHDIA – lunettes de soleil Vintage en aluminium + TR90, verres photochromiques polarisés UV400, à la mode,",
      rate: 3,
      sexe:'h',
      prix: '25 TND',
      livraison: 'y',
      disponibilite: 'nd',
    },
    {
      id: "3",
      title: "veste",
      poster: "https://ae01.alicdn.com/kf/S2e3b7cd2f669448488aa04de8ef8dcddS/New-Autumn-and-Winter-Men-s-Round-Neck-Loose-Jacket-Thickened-Jacket-Baseball-Uniform-Trendy-Men.jpg_220x220xz.jpg_.webp",
      decription: "Veste ample épaissie à col rond pour hommes, uniforme de Baseball, vêtements tendance de haute qualité, 5xl, nouvelle collection automne et hiver 2022",
      rate: 1,
      sexe:'h',
      prix: '150 TND',
      livraison: 'y',
      disponibilite: 'd',
    },
    {
      id: "4",
      title: "veste cuire",
      poster: "https://ae01.alicdn.com/kf/Sab164f33de7240f4a9e8513f065cac51i/2021-Spring-Mens-Bomber-Jackets-Fashion-Men-Faux-Leather-Coat-Zipper-Overcoat-Motor-Jacket-Motorcycle-Bikers.jpg_220x220xz.jpg_.webp",
      decription: "Blouson en similicuir homme, à la mode, avec fermeture éclair, pour motard, printemps 2021",
      rate: 3,
      sexe:'h',
      prix: '200 TND',
      livraison: 'n',
      disponibilite: 'd',
    },
    {
      id: "5",
      title: "robe veste",
      poster:
        "https://ae01.alicdn.com/kf/S54028293e4bf4f7282bebc337608ce047/SINGREINY-PU-Leather-Jacket-Long-Sleeves-Women-Belt-Fashion-Solid-Winter-2022-Fashion-Ladies-Harajuku-Warm.jpg_220x220xz.jpg_.webp",
      decription: "The Ring is a 2002 American supernatural horror film",
      rate: 3,
      sexe:'f',
      prix: '99.95 TND',
      livraison: 'n',
      disponibilite: 'nd',

    },
    {
      id: "6",
      title: "robe soiree",
      poster:
        "https://ae01.alicdn.com/kf/S11276ba9e4a24d599b3962517a6df3a61/Sexy-Mint-Green-Mermaid-Evening-Dress-Lace-V-Neck-Full-Sleeve-Evening-Dress-Custom-Women-s.jpg_220x220xz.jpg_.webp",
      decription: "The Ring is a 2002 American supernatural horror film",
      rate: 3,
      sexe:'f',
      prix: '300 TND',
      livraison: 'y',
      disponibilite: 'd',
    },
    {
      id: "7",
      title: "sac a dos femme",
      poster: "https://ae01.alicdn.com/kf/S84ff5c4bdc184b2e9f139d281b0d3817w/Backpacks-For-Students-Canvas-Black-School-Bags-for-Girls-Shoulder-Travel-Bag-Fashion-Kawaii-Small-Backpack.jpg_220x220xz.jpg_.webp",
      decription: "The Ring is a 2002 American supernatural horror film",
      rate: 2,
      sexe:'f',
      prix: '80 TND',
      livraison: 'y',
      disponibilite: 'nd',
    },
    {
      id: "8",
      title: "sac a dos homme",
      poster: "https://ae01.alicdn.com/kf/H903a7cb3d2164e9785ccb9452d5003eea/Men-Backpacks-80L-Waterproof-Oxford-For-Teenagers-School-Students-Bag-Casual-Outdoor-Travel-Rucksack-Trekking-Backpack.jpeg_220x220xz.jpeg_.webp",
      decription: "The Ring is a 2002 American supernatural horror film",
      rate: 4,
      sexe:'f',
      prix: '90 TND',
      livraison: 'y',
      disponibilite: 'd',
    },
    {
        id: "9",
        title: "chemise",
        poster: "https://ae01.alicdn.com/kf/Sba7bd59e5d124f338b9c59f2a185be5e5/Men-s-long-sleeved-linen-shirt-cotton-and-linen-casual-shirt-s-5xl-top-brand-new.jpg_220x220xz.jpg_.webp",
        decription: "Chemise en lin à manches longues pour hommes, haut décontracté en coton et lin, neuf, s-5xl, livraison gratuite",
        rate: 4,
        sexe:'h',
        prix: '110 TND',
        livraison: 'n',
        disponibilite: 'nd',
      },
      
      
  ];
  